version: "3"

services:

  server:

    build: server/
    
    ports:
      - 5000:5000
      
      
  client:

    build: client/
    
    ports:
      - 8080:8080
    
    devices:
      - /dev/video0:/dev/video0
        

    depends_on:
      - server