version: "3"

services:

  server:

    build: server/
    
    volumes:
      - ${PWD}:${PWD}

    
    ports:
      - 5000:5000
      
      
    privileged: true  
      
  client:

    build: client/
    
    volumes:
        - ./server:/server
    
    ports:
      - 8080:8080


    depends_on:
      - server
      
    privileged: true
